scheming_version: 2
schema_id: mailcraft_config
about: Configuration options for the DOI extension

fields:
  - field_name: ckanext.mailcraft.test_conn_on_startup
    label: Test connection on startup
    validators: default(true), one_of([true, false])
    preset: select
    required: true
    choices:
      - value: true
        label: Enabled
      - value: false
        label: Disabled

  - field_name: ckanext.mailcraft.conn_timeout
    label: Connection timeout
    description: Specify a timeout for an SMTP connection
    input_type: number
    required: true
    validators: default(10), int_validator

  - field_name: ckanext.mailcraft.stop_outgoing_emails
    label: Stop outgoing emails
    validators: default(true), one_of([true, false])
    preset: select
    required: true
    choices:
      - value: true
        label: Enabled
      - value: false
        label: Disabled

  - field_name: ckanext.mailcraft.redirect_emails_to
    label: Redirect emails to
    description: Redirect outgoing emails to a specified email1
    validators: ignore_empty, unicode_safe, email_validator
