version: 1
groups:
  - annotation: mailcraft
    options:
      - key: ckanext.mailcraft.test_conn_on_startup
        type: bool
        description: Check SMTP connection when CKAN starts
        default: false
        editable: true

      - key: ckanext.mailcraft.conn_timeout
        type: int
        description: Timeout (in seconds) for establishing an SMTP connection
        default: 10
        editable: true

      - key: ckanext.mailcraft.stop_outgoing_emails
        type: bool
        description: If enabled, outgoing emails will not be sent
        default: false
        editable: true

      - key: ckanext.mailcraft.save_emails
        type: bool
        description: Save outgoing emails to the database
        default: false
        editable: true

      - key: ckanext.mailcraft.redirect_emails_to
        description: Redirect outgoing emails to a specified email addresses
        editable: true
        type: list
        example: john@example.com alice@example.com
